.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH TINT3 1 "2014-07-19"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
tint3 \- lightweight panel/taskbar
.SH SYNOPSIS
.B tint3
.br
.B tint3
.RI -c
.IR /path_to_config_file
.SH DESCRIPTION
This manual page documents briefly the
.B tint3
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBtint3\fP is a simple panel/taskbar intentionally made for OpenBox, but
should also work with other window managers.
It's based on the original tint2 code.
.PP
On the first startup tint3 creates a config file in $HOME/.config/tint3/tint3rc.
.PP
See the README on https://github.com/jmc-88/tint3 for more information.
.SH OPTIONS
.TP
.B \-c config-file
Specify which configuration file to use instead of the default.
.SH AUTHOR
tint3 was written by Daniele Cocca (https://github.com/jmc-88).  It is based on
tint2, written by Thierry Lorthiois <lorthiois@bbsoft.fr>, in turn based on
ttm, originally written by Pål Staurland <staura@gmail.com>.
.PP
This manual page was written by Daniel Moerner <dmoerner@gmail.com>,
for the Debian project (but may be used by others).  It was adopted from the
tint3 docs.
