#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1; then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

# Reformat C++ files with ClangFormat.
git diff-index --name-only --cached "${against}" -- \
  | grep -E '(\.cc|\.h)$' \
  | while read file; do
  clang-format -i -style=google "${file}" && {
    git add "${file}"
  } || exit $?
done

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached "${against}" --
