#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Immediately fail on errors.
set -e

# Redirect output to stderr.
exec 1>&2

# Reformat C++ files with Artistic Style.
for file in $(git diff --cached --name-only | grep '\.(cc|h)$'); do
    exec astyle --options=.astylerc "${file}"
done

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached "${against}" --
