# Per-generator CPack configuration file.
# https://cmake.org/cmake/help/v3.0/module/CPack.html#variable:CPACK_PROJECT_CONFIG_FILE

if(CPACK_GENERATOR STREQUAL "DEB")
  set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_SYSTEM_NAME}")
endif()

if(CPACK_GENERATOR STREQUAL "RPM")
  set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_RPM_PACKAGE_RELEASE}.${CPACK_SYSTEM_NAME}")
endif()
